FROM nginx:alpine

# Copy compiled React app (lovable version)
COPY lovable_website_version/dist/ /usr/share/nginx/html/

COPY nginx-website2.conf /etc/nginx/conf.d/default.conf.template

EXPOSE 8080

CMD ["/bin/sh", "-c", "envsubst '$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
