#!/bin/bash
# Report which agent-relevant env vars are set/empty (lengths only, no values).
set -e
for v in \
  HF_API_KEY HF_ENABLED HF_COST_CAP_USD \
  OPENROUTER_API_KEY OPENROUTER_MODEL OPENROUTER_ENABLED \
  CEREBRAS_API_KEY CEREBRAS_MODEL CEREBRAS_ENABLED \
  GROQ_API_KEY GROQ_MODEL GROQ_ENABLED \
  GITHUB_MODELS_TOKEN GITHUB_PAT GITHUB_MODELS_ENABLED \
  OPENAI_API_KEY CHATGPT_ENABLED \
  GEMINI_B_SESSION_TOKEN GEMINI_API_KEY_B GEMINI_B_ENABLED \
  CLAUDE_ACCOUNT_B_SESSION_TOKEN CLAUDE_ACCOUNT_B_SESSION_TAR \
  KIMI_SESSION_TOKEN \
  LEGION_API_SHARED_SECRET PRIMARY_BEACON_SECRET PG_DSN \
  SUPER_AGENT_BASE_URL N8N_MAGIC_LINK_WEBHOOK
do
  val="${!v}"
  if [ -n "$val" ]; then
    echo "$v=<set,${#val}b>"
  else
    echo "$v=<empty>"
  fi
done
