"""
Bridge Company — Phase 0 bootstrap.

Creates gelson12/bridge_websites_demos, enables GitHub Pages on main/root,
commits _template/index.html, _template/css/style.css, README.md, and a
dummy test/index.html, then polls the expected Pages URL until 200.

Run once locally (or from inspiring-cat):
    python scripts/bridge_phase0_bootstrap.py

Requires GITHUB_PAT in the environment (already set in super-agent/.env).
Idempotent: re-running when the repo already exists is safe — it will skip
creation, re-assert Pages, and overwrite the template files.
"""

from __future__ import annotations
import os
import sys
import time
import base64
from pathlib import Path

import requests
from github import Github, GithubException

REPO_OWNER = "gelson12"
REPO_NAME = "bridge_websites_demos"
DEFAULT_BRANCH = "main"
PAGES_URL = f"https://{REPO_OWNER}.github.io/{REPO_NAME}"

TEMPLATE_INDEX_HTML = """\
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{meta_title}}</title>
  <meta name="description" content="{{meta_description}}">
  <link rel="stylesheet" href="../_template/css/style.css">
</head>
<body>
  <header class="hero">
    <h1>{{hero_h1}}</h1>
    <p class="hero-sub">{{hero_sub}}</p>
    <a class="cta" href="#contact">{{cta_primary}}</a>
  </header>

  <section class="services">
    <h2>Services</h2>
    <div class="cards">{{service_cards_html}}</div>
  </section>

  <section class="why-us">
    <h2>Why choose us</h2>
    <ul>{{why_us_html}}</ul>
  </section>

  <section class="areas">
    <h2>Service areas</h2>
    <p>{{service_areas}}</p>
  </section>

  <section id="contact" class="contact">
    <h2>Get in touch</h2>
    <p>{{contact_html}}</p>
    <p class="bridge-signature">
      Demo built by Bridge Digital Solution &middot;
      <a href="mailto:bridge.digital.solution@gmail.com">bridge.digital.solution@gmail.com</a> &middot;
      <a href="https://wa.me/447345787028">WhatsApp +44 7345 787028</a>
    </p>
  </section>

  <footer>{{footer_html}}</footer>
</body>
</html>
"""

TEMPLATE_CSS = """\
:root {
  --brand: #1b3a5b;
  --accent: #e0a43a;
  --bg: #fafafa;
  --fg: #1a1a1a;
  --muted: #6b6b6b;
}
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font: 16px/1.55 system-ui, -apple-system, Segoe UI, Roboto, sans-serif;
       color: var(--fg); background: var(--bg); }
.hero { padding: 4rem 1.5rem; text-align: center; background: var(--brand); color: #fff; }
.hero h1 { font-size: clamp(1.8rem, 4vw, 2.6rem); margin-bottom: 1rem; }
.hero-sub { max-width: 40rem; margin: 0 auto 1.5rem; opacity: .9; }
.cta { display: inline-block; padding: .8rem 1.6rem; background: var(--accent);
       color: #111; text-decoration: none; border-radius: 4px; font-weight: 600; }
section { padding: 3rem 1.5rem; max-width: 60rem; margin: 0 auto; }
section h2 { margin-bottom: 1.2rem; color: var(--brand); }
.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(14rem, 1fr)); gap: 1rem; }
.card { padding: 1.2rem; background: #fff; border: 1px solid #eee; border-radius: 6px; }
.why-us ul { padding-left: 1.2rem; }
.why-us li { margin-bottom: .5rem; }
.contact { text-align: center; }
.bridge-signature { margin-top: 1rem; font-size: .85rem; color: var(--muted); }
footer { padding: 1.5rem; text-align: center; font-size: .85rem; color: var(--muted); }
"""

README_MD = """\
# bridge_websites_demos

Demo websites auto-generated by the Bridge Company pipeline
(see `gelson12/super-agent` → `n8n/bridge_website_builder.json`).

Each prospect's demo lives at `/{slug}/index.html` and is served by GitHub Pages at
https://gelson12.github.io/bridge_websites_demos/{slug}/

Demos are auto-deleted after 12 hours unless the prospect accepts the offer.
The `_template/` folder is the base template injected by the builder workflow.

Do not hand-edit this repo — all content is machine-generated.
"""

TEST_INDEX_HTML = """\
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Bridge Company — Pages test</title></head>
<body style="font-family:system-ui;padding:2rem">
  <h1>Bridge Company Phase-0 test page</h1>
  <p>If you can read this at
    <code>https://gelson12.github.io/bridge_websites_demos/test/</code>,
    GitHub Pages is serving the demos repo correctly.</p>
</body></html>
"""


def load_pat() -> str:
    pat = os.environ.get("GITHUB_PAT")
    if pat:
        return pat
    # Fallback: read from ../.env relative to this script
    env_path = Path(__file__).resolve().parent.parent / ".env"
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line.startswith("GITHUB_PAT="):
                return line.split("=", 1)[1].strip().strip('"').strip("'")
    sys.exit("[FATAL] GITHUB_PAT not found in env or ../.env")


def ensure_repo(gh: Github) -> "github.Repository.Repository":
    user = gh.get_user()
    try:
        repo = gh.get_repo(f"{REPO_OWNER}/{REPO_NAME}")
        print(f"[OK]   Repo already exists: {repo.full_name}")
        return repo
    except GithubException as e:
        if e.status != 404:
            raise
    print(f"[..]   Creating repo {REPO_OWNER}/{REPO_NAME} ...")
    repo = user.create_repo(
        name=REPO_NAME,
        description="Bridge Company — auto-generated demo websites for prospects (machine-managed)",
        private=False,
        auto_init=True,
    )
    print(f"[OK]   Created {repo.full_name} (default_branch={repo.default_branch})")
    return repo


def enable_pages(pat: str) -> None:
    url = f"https://api.github.com/repos/{REPO_OWNER}/{REPO_NAME}/pages"
    headers = {
        "Authorization": f"Bearer {pat}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    body = {"source": {"branch": DEFAULT_BRANCH, "path": "/"}}
    r = requests.post(url, headers=headers, json=body, timeout=20)
    if r.status_code in (201, 204):
        print(f"[OK]   Pages enabled — will serve at {PAGES_URL}/")
    elif r.status_code == 409:
        print(f"[OK]   Pages already enabled at {PAGES_URL}/")
    else:
        print(f"[WARN] Pages enable returned {r.status_code}: {r.text}")


def put_file(repo, path: str, content: str, msg: str) -> None:
    encoded = content.encode("utf-8")
    try:
        existing = repo.get_contents(path, ref=DEFAULT_BRANCH)
        repo.update_file(path, msg, encoded, existing.sha, branch=DEFAULT_BRANCH)
        print(f"[OK]   Updated {path}")
    except GithubException as e:
        if e.status != 404:
            raise
        repo.create_file(path, msg, encoded, branch=DEFAULT_BRANCH)
        print(f"[OK]   Created {path}")


def wait_for_pages(url: str, timeout_s: int = 180) -> bool:
    print(f"[..]   Polling {url} (up to {timeout_s}s) ...")
    deadline = time.time() + timeout_s
    while time.time() < deadline:
        try:
            r = requests.get(url, timeout=10)
            if r.status_code == 200:
                print(f"[OK]   Pages live ({r.status_code}, {len(r.text)} bytes)")
                return True
            print(f"       ... {r.status_code}")
        except requests.RequestException as e:
            print(f"       ... {e.__class__.__name__}")
        time.sleep(10)
    print(f"[WARN] Pages did not return 200 within {timeout_s}s — may still propagate.")
    return False


def main() -> int:
    pat = load_pat()
    gh = Github(pat)
    repo = ensure_repo(gh)
    enable_pages(pat)

    put_file(repo, "_template/index.html", TEMPLATE_INDEX_HTML,
             "chore: seed _template/index.html (Bridge Company phase 0)")
    put_file(repo, "_template/css/style.css", TEMPLATE_CSS,
             "chore: seed _template/css/style.css")
    put_file(repo, "README.md", README_MD,
             "chore: project readme")
    put_file(repo, "test/index.html", TEST_INDEX_HTML,
             "chore: test page to verify GitHub Pages serves /{slug}/")

    # Pages can take up to ~90s to publish the first build.
    ok = wait_for_pages(f"{PAGES_URL}/test/", timeout_s=180)

    print("\nPhase 0 bootstrap summary:")
    print(f"  Repo   : https://github.com/{REPO_OWNER}/{REPO_NAME}")
    print(f"  Pages  : {PAGES_URL}/")
    print(f"  Test   : {PAGES_URL}/test/   {'(200 OK)' if ok else '(propagating...)'}")
    print(f"  Template: {PAGES_URL}/_template/  (not meant to be hit directly)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
